name: dev

concurrency: ${{ github.workflow }}

on:
  workflow_dispatch:

jobs:
  job-1:
    name: Job 1
    runs-on: ubuntu-latest
    environment: ${{ github.workflow }}

    steps:
    - run: echo "this is ${{ github.workflow }}"
