name: sbx

concurrency: ${{ github.workflow }}

on:
  pull_request:
    branches: [main, Sprint_*]
    paths-ignore:
    - '.gitignore'
    - '**/*.md'
    - 'LICENSE'

jobs:
  job-1:
    name: Job 1
    runs-on: ubuntu-latest
    environment: ${{ github.workflow }}

    steps:
    - name: Checkout Branch
      uses: actions/checkout@v3

    - run: echo "${{ github.ref }}"

  run-dev:
    name: Start Dev Workflow
    if: ${{ github.event_name == 'pull_request' && contains(fromJSON('["refs/heads/main", "refs/heads/sprint_1"]'), github.ref) && success() }}
    needs: [job-1] # Add all workflow jobs to needs to alert on failure.
    runs-on: ubuntu-latest
    environment: ${{ github.workflow }}

    steps:
    - name: Dispatch Dev Workflow
      uses: benc-uk/workflow-dispatch@v1
