name: sbx

concurrency: ${{ github.workflow }}

on:
  pull_request:
    branches: [main, Sprint_*]
    paths-ignore:
    - '.gitignore'
    - '**/*.md'
    - 'LICENSE'

jobs:
  job-1:
    name:    Job 1
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Branch
      uses: actions/checkout@v3
